name: Build debian

on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        codename: [focal, jammy, kinetic, lunar]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get build dependencies
        run: |
          sudo apt install pbuilder devscripts equivs
          sudo mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
      - name: Make source
        run: |
          python3 updateChangelog.py ${{ matrix.codename }}
          dpkg-buildpackage -S -sa
          mkdir source
          mv ../python*.* source/
      - name: Import key
        run: |
          GPG_KEY_ID=$(echo "${{ secrets.PPA_GPG_PRIVATE_KEY }}" | gpg --import-options show-only --import | sed -n '2s/^\s*//p')
          echo $GPG_KEY_ID
          echo "${{ secrets.PPA_GPG_PRIVATE_KEY }}" | gpg --batch --import
          debsign source/*.changes
      - name: Build
        run: |
          sudo pbuilder create \
            --distribution ${{ matrix.codename }}
          sudo pbuilder build \
            --distribution ${{ matrix.codename }} \
            --buildresult .. \
            source/*dsc
          mkdir binary
          mv ../python*.* binary/
      - name: Upload debian package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.codename }}
          path: |
            source
            binary
      - name: Publish package to prerelease PPA
        run: |
          sudo apt install dput
          dput ppa:slaclau/ppa-pre source/*source.changes
        if: github.ref == 'refs/heads/master' 
